export default {
    //App
    SET_LOADING_FINISH: "@@APP/SET_LOADING_FINISH",
    SET_LOADING: "@@APP/SET_LOADING",
    SET_ERROR_MSG: "@@APP/SET_ERROR_MSG",


    //Auth
    LOGIN: "@@AUTH/LOGIN",
    LOGOUT: "@@AUTH/LOGOUT",

    //User
    RETRIEVE_RECORD: "@USER/RETRIEVE_RECORD"
}
