export default {
    //App
    SET_LOADING_FINISH: "@@APP/SET_LOADING_FINISH",
    SET_LOADING: "@@APP/SET_LOADING",
    SET_ERROR_MSG: "@@APP/SET_ERROR_MSG",
    SET_MODAL_OPEN: "@@APP/OPEN_MODAL",
    SET_MODAL_CLOSE: "@@APP/CLOSE_MODAL",


    //Auth
    LOGIN: "@@AUTH/LOGIN",
    LOGOUT: "@@AUTH/LOGOUT",


    //User
    SET_CONSULTATION_RECORD: "@USER/RETRIEVE_RECORD"
}
